#!/bin/bash

PYTHON_VERSION="2.7.9"
VIRTUALENV_VERSION="15.0.1"

Check for Python and install if absent
if [ ! -f $OPENSHIFT_DATA_DIR/bin/python ]; then
    cd $OPENSHIFT_TMP_DIR
    wget http://www.python.org/ftp/python/${PYTHON_VERSION}/Python-${PYTHON_VERSION}.tar.xz
    tar Jxf Python-${PYTHON_VERSION}.tar.xz
    cd Python-${PYTHON_VERSION}
    ./configure --prefix=$OPENSHIFT_DATA_DIR
    make install
fi

# Check for virtualenv and install if absent
if [ ! -f $OPENSHIFT_DATA_DIR/bin/virtualenv ]; then
    $OPENSHIFT_DATA_DIR/bin/pip install virtualenv
    # $OPENSHIFT_DATA_DIR/bin/pip install virtualenv
fi

# Check for existing virtual environment and install if there isn't one
if [ ! -d $OPENSHIFT_HOMEDIR/python/virtenv/venv ]; then
    $OPENSHIFT_DATA_DIR/bin/virtualenv -p $OPENSHIFT_DATA_DIR/bin/python $OPENSHIFT_DATA_DIR/bin/venv
fi

# Cleanup
rm -rf $OPENSHIFT_TMP_DIR/*
